services:
  # proxy:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
  #   ports:
  #     - "80:80"

  api:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - shinyhunter-net

  reactf:
    build: ./reactf
    restart: unless-stopped
    volumes:
      - ./reactf/src:/app/src
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      BACKEND_ADDRESS: http://api:80
    networks:
      - shinyhunter-net

  database:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount a volume for mariadb's persistent files for lifecycle outside of stack
      - "./db/data:/var/lib/mysql"
      # Mount the db_schema into the container to be auto-read and created in the new db
      - "./db/db_schema/shinyhunter.sql:/docker-entrypoint-initdb.d/shinyhunter.sql"
    env_file:
      - .env
    networks:
      - shinyhunter-net

  images:
    build: ./images
    restart: unless-stopped
    volumes:
      - ./images/:/app/
    env_file:
      - .env
    networks:
      - shinyhunter-net
  
networks:
  shinyhunter-net:
