services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src
    environment:
      - PORT=80

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
    environment:
      - PORT=80
